stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - data/raw/dataset.csv

  validate:
    cmd: python src/validate_data.py
    deps:
      - src/validate_data.py
      - data/raw/dataset.csv

  preprocess:
    cmd: python src/preprocessing.py
    deps:
      - src/preprocessing.py
      - data/raw/dataset.csv
    outs:
      - data/processed
      - models/scaler.pkl
      - models/feature_columns.json
      - models/label_encoders.pkl

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed
    outs:
      - models/model.pkl
      - models/model_metadata.json

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - data/processed
      - models/model.pkl
    metrics:
      - metrics.txt:
          cache: false

  register:
    cmd: python src/register_model.py
    deps:
      - src/register_model.py
      - models/model.pkl
      - models/model_metadata.json
